services:
  tms-ws:
    build: .
    networks:
      - eurekadiscoveryserver_mms-network
    ports:
      - "8090:8090"

  tms-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    networks:
      - eurekadiscoveryserver_mms-network
    ports:
      - "5462:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

networks:
  eurekadiscoveryserver_mms-network:
    external: true

volumes:
  db-volume: