server:
  port: 8090
spring:
  application:
    name: TopicManagementService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mms_tms_db
    username: postgres
    password: abcd1234
    port: 5432
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: postgres